module.exports = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<title>Service Worker TEST</title>',
    '</head>',
    '<body>',
    '<h1>About</h1>',
    '<p>Served by Express framework</p>',
    '<p><a href="/">index page</a></p>',
    '<p><a href="/test">test page</a></p>',
    '</body>',
    '</html>',
].join('');
